/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DurationRange {
  start: number
  end: number
}
export interface TimestampRange {
  start: string
  end: string
}
export interface ExpressionCandidate {
  start: number
  end: number
  text: string
}
export declare function between(startRfc3339: string, endRfc3339: string, locale?: string | undefined | null, useNativeKoNumber?: boolean | undefined | null): string
export declare function fromDuration(seconds: number, isFuture?: boolean | undefined | null, locale?: string | undefined | null, useNativeKoNumber?: boolean | undefined | null): string
export declare function rangeOf(expression: string, locale?: string | undefined | null): DurationRange
export declare function resolveDurationRange(start: number, end: number, anchorRfc3339?: string | undefined | null): TimestampRange
export declare function rangeOfTimestamps(expression: string, locale?: string | undefined | null, anchorRfc3339?: string | undefined | null): TimestampRange
export declare function extractExpressions(input: string, locale?: string | undefined | null): Array<ExpressionCandidate>
