/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function between(startRfc3339: string, endRfc3339: string, locale?: string | undefined | null, useNativeKoNumber?: boolean | undefined | null): string
export declare function fromDuration(seconds: number, isFuture?: boolean | undefined | null, locale?: string | undefined | null, useNativeKoNumber?: boolean | undefined | null): string
